import StyledComponentsRegistry from "@/components/StyledComponentsRegistry";

export const metadata = {
  title: "NASA Photos Gallery",
  description: "Generated by Luke Liu",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  );
}
